apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"team-serving","namespace":"team"},"spec":{"ports":[{"name":"http","port":8000,"targetPort":8000}],"selector":{"app":"vllm"}}}
  creationTimestamp: "2026-09-08T12:26:32Z"
  name: team-serving
  namespace: team
  resourceVersion: "230140"
  uid: 377ebf2a-0702-41e9-a66d-c750109d4f35
spec:
  clusterIP: 10.43.84.121
  clusterIPs:
  - 10.43.84.121
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30800
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: vllm
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
